CACHE MANIFEST
# <%= grunt.template.today("yyyy-mm-dd hh:MM:ss") %>

CACHE:
index.html
js/Groceries.min.js
js/angular/angular.min.js
js/angular/angular-cookies.min.js
js/angular/angular-mobile.min.js
js/angular-local-storage/angular-local-storage.js
css/screen.css
css/topcoat-desktop-dark.min.css
css/topcoat-mobile-dark.min.css
img/avatar.png
img/bg_dark.png
img/breadcrumb.png
img/checkbox_checked.png
img/checkbox_checked_dark.png
img/checkbox_unchecked.png
img/checkbox_unchecked_dark.png
img/checkmark_bw.svg
img/dark-combo-box-bg.png
img/dark-combo-box-bg2x.png
img/dark-grips.png
img/dark-sprites2x.png
img/dialog-zone-bg.png
img/drop-down-triangle-dark.png
img/drop-down-triangle.png
img/hamburger_bw.svg
img/hamburger_dark.svg
img/hamburger_light.svg
img/light-combo-box-bg.png
img/light-combo-box-bg2x.png
img/light-grips.png
img/light-sprites2x.png
img/logo.png
img/pop-up-triangle-dark.png
img/pop-up-triangle.png
img/search-bg.png
img/search-bg2x.png
img/search.svg
img/search_bw.svg
img/search_dark.svg
img/search_light.svg
img/spinner.png
img/spinner2x.png

NETWORK:
*